name: flutter_chess_board
description: A Chessboard Widget for Flutter. Full support for PGN, FEN, SAN. Undo move, multiple board colors and arrow support.
version: 1.0.1
repository: https://www.github.com/deven98/flutter_chess_board

dependencies:
  chess: ^0.8.1
  chess_vectors_flutter: ^1.0.12

  flutter:
    sdk: flutter
  #image: ^4.2.0

environment:
    sdk: ">2.12.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/chess_board.png
    - images/brown_board.png
    - images/2.0x/brown_board.png
    - images/3.0x/brown_board.png
    - images/orange_board.png
    - images/2.0x/orange_board.png
    - images/3.0x/orange_board.png
    - images/green_board.png
    - images/2.0x/green_board.png
    - images/3.0x/green_board.png
    - images/dark_brown_board.png
    - images/2.0x/dark_brown_board.png
    - images/3.0x/dark_brown_board.png
    # - images/boards/
    - images/piece_sets/
    - images/piece_sets/alpha/
    - images/piece_sets/anarcandy/
    - images/piece_sets/caliente/
    - images/piece_sets/california/
    - images/piece_sets/cardinal/
    - images/piece_sets/cburnett/
    - images/piece_sets/celtic/
    - images/piece_sets/chess7/
    - images/piece_sets/chessnut/
    - images/piece_sets/companion/
    - images/piece_sets/disguised/
    - images/piece_sets/dubrovny/
    - images/piece_sets/fantasy/
    - images/piece_sets/fresca/
    - images/piece_sets/gioco/
    - images/piece_sets/governor/
    - images/piece_sets/horsey/
    - images/piece_sets/icpieces/
    - images/piece_sets/kiwen-suwi/
    - images/piece_sets/kosal/
    - images/piece_sets/leipzig/
    - images/piece_sets/letter/
    - images/piece_sets/libra/
    - images/piece_sets/maestro/
    - images/piece_sets/merida/
    - images/piece_sets/mole/
    - images/piece_sets/mono/
    - images/piece_sets/mpchess/
    - images/piece_sets/pirouetti/
    - images/piece_sets/pixel/
    - images/piece_sets/reillycraig/
    - images/piece_sets/riohacha/
    - images/piece_sets/shapes/
    - images/piece_sets/staunty/
    - images/piece_sets/tatiana/
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
